title: SDG Translations
description: >-
  SDG Translations makes it easy to translate text related to the
  United Nation's "Sustainable Development Goals", and to keep those
  translations available in one place, in both machine-friendly and
  translator-friendly formats.
baseurl: "/sdg-translations"
url: "https://opendataenterprise.github.io"

# Build settings
markdown: kramdown
source: www
theme: uswds-jekyll

keep_files:
  - "*.json"
  - "*.csv"
