# Python CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - save_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Validate the translation data.
          command: |
            . venv/bin/activate
            python3 scripts/check_translations.py
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - save_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Build the translation data.
          command: |
            . venv/bin/activate
            python3 scripts/build_translations.py
      - run:
          name: Export the current languages for translation.
          command: |
            . venv/bin/activate
            python3 scripts/export_languages.py
      - persist_to_workspace:
          root: ~/repo
          paths:
            - _site
  deploy:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cf:b6:38:eb:f2:68:37:dd:6e:49:53:66:ac:c1:40:15"
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/deploy_staging.circleci.sh
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop